-- Worker runs moved to GitHub Actions, so the dashboard needs somewhere to
-- watch them from.
--
-- A render used to be a child process whose stdout the dashboard tailed
-- directly. On a runner there is no pipe to tail: Actions only exposes a run's
-- logs once it has finished, which would leave the operator watching a blank
-- screen for the several minutes a render takes.
--
-- So the runner ships its stdout here, line by line, and the dashboard streams
-- from these tables instead. The log lines themselves are unchanged, which is
-- what lets the existing progress UI keep working without knowing where the
-- job actually ran.

create table worker_jobs (
  -- Generated by the dashboard before dispatching, and used as the workflow's
  -- run-name: `workflow_dispatch` returns no run id, so this is how a run is
  -- found again afterwards.
  id             text primary key check (id ~ '^[a-z0-9-]{8,64}$'),
  command        text not null,
  inputs         jsonb not null default '{}'::jsonb,
  status         text not null default 'queued' check (status in (
                   'queued',    -- dispatched, runner not yet started
                   'running',
                   'done',
                   'failed',
                   'cancelled'
                 )),
  -- Filled in once the run has been located via the Actions API.
  github_run_id  bigint,
  exit_code      integer,
  -- The drop folder the render produced, parsed from the worker's output.
  drop_dir       text,
  error_message  text,
  created_at     timestamptz not null default now(),
  started_at     timestamptz,
  ended_at       timestamptz
);

create index worker_jobs_created_idx on worker_jobs (created_at desc);
create index worker_jobs_active_idx on worker_jobs (status) where status in ('queued', 'running');

alter table worker_jobs enable row level security;


create table worker_job_logs (
  job_id text not null references worker_jobs (id) on delete cascade,
  -- Monotonic per job. The dashboard streams with `seq > last_seen`, so a
  -- browser that reconnects resumes exactly where it stopped rather than
  -- replaying the whole run or silently skipping its middle.
  seq    integer not null,
  line   text not null,
  at     timestamptz not null default now(),
  primary key (job_id, seq)
);

create trigger worker_job_logs_immutable
  before update or delete on worker_job_logs
  for each row execute function forbid_mutation();

alter table worker_job_logs enable row level security;


-- Drop folders produced by a run. Replaces reading the worker's local output/
-- directory, which no longer exists anywhere the dashboard can see.
create table drops (
  dir         text primary key,
  job_id      text references worker_jobs (id),
  created_at  timestamptz not null default now(),
  pdf         text,
  reels       jsonb not null default '[]'::jsonb,
  asset_count integer not null default 0
);

create index drops_created_idx on drops (created_at desc);

alter table drops enable row level security;
